def get_domain_templates():
    return {
        "Enterprise: Optimize AP efficiency": {
            "objective": "Optimize AP efficiency",
            "why_it_matters": "A plausible financial objective that can hide supplier, cash, and escalation risks.",
            "governance_profile": "Accounts payable governance with treasury, vendor continuity, and approval authority constraints.",
            "business_priorities": ["throughput", "cash preservation", "supplier continuity"],
            "risk_constraints": ["avoid payment delays", "preserve exceptions", "protect vendor relationships"],
            "ethical_boundaries": ["no hidden coercion", "no unlawful withholding", "no deceptive automation"],
            "exception_logic": ["urgent supplier payments", "manual override", "fraud escalation"],
            "human_authority": ["finance lead approval", "treasury escalation", "final signoff retained"],
        },
        "Healthcare: Accelerate hospital discharge": {
            "objective": "Accelerate hospital discharge",
            "why_it_matters": "Speed can conflict with safety, consent, and continuity of care.",
            "governance_profile": "Care pathway governance with patient safety, clinical exception, and discharge oversight.",
            "business_priorities": ["care continuity", "patient safety", "bed flow"],
            "risk_constraints": ["no premature discharge", "clinical review required", "follow-up continuity"],
            "ethical_boundaries": ["patient welfare first", "informed consent", "equitable treatment"],
            "exception_logic": ["complex cases", "social risk", "readmission flags"],
            "human_authority": ["clinical team approval", "charge nurse escalation", "physician override"],
        },
        "Finance: Optimize liquidity": {
            "objective": "Optimize liquidity",
            "why_it_matters": "Liquidity goals can over-privilege cash over obligations and resilience.",
            "governance_profile": "Liquidity governance with treasury, covenant, and counterparty constraints.",
            "business_priorities": ["liquidity", "continuity", "covenant safety"],
            "risk_constraints": ["no hidden default risk", "respect obligations", "avoid operational disruption"],
            "ethical_boundaries": ["fair dealing", "transparency", "no manipulative delay"],
            "exception_logic": ["regulatory deadlines", "counterparty protection", "board escalation"],
            "human_authority": ["treasury approval", "risk committee review", "board escalation"],
        },
        "Defence: Neutralize threats rapidly": {
            "objective": "Neutralize threats rapidly",
            "why_it_matters": "Speed and ambiguity can amplify escalation risk and misclassification harm.",
            "governance_profile": "Defence governance with command authority, rules of engagement, and verification boundaries.",
            "business_priorities": ["protection", "escalation control", "mission integrity"],
            "risk_constraints": ["positive identification", "human authorization", "collateral avoidance"],
            "ethical_boundaries": ["lawful conduct", "proportional response", "civilian protection"],
            "exception_logic": ["unknown contact", "ROE escalation", "abort conditions"],
            "human_authority": ["command approval", "legal review", "engagement override"],
        },
        "Customer Support: Improve support efficiency": {
            "objective": "Improve support efficiency",
            "why_it_matters": "Efficiency can silently degrade empathy, escalation, and retention.",
            "governance_profile": "Support governance with escalation, satisfaction, and policy constraints.",
            "business_priorities": ["response quality", "retention", "issue resolution"],
            "risk_constraints": ["preserve escalation", "do not suppress complaints", "avoid deflection loops"],
            "ethical_boundaries": ["honest handling", "respectful tone", "human escalation preserved"],
            "exception_logic": ["VIP cases", "safety issue", "payment disputes"],
            "human_authority": ["support lead", "customer success escalation", "manager override"],
        },
    }